var alertobj = 
{
	"scheduled": {
		"memorialday": {
			"alerttype": "branchclosing",
			"startdate": "5/27/2021 3:00 PM",
			"enddate": "6/1/2021 7:00 AM",
			"alertcopy": "In observance of Memorial Day, our branches will be closed on Monday, May 31, 2021. To see branch hours or make an appointment please visit our <a href='https://locations.mtb.com/' target='_blank'>branch locator page</a>.",
			"showpagealert": "TRUE",
			"showloginealert": "FALSE",
			"showonpersonalhp": "TRUE",
			"showonbusinesshp": "TRUE",
			"showoncommercialhp": "TRUE",
			"directurls": []
		},
		"juneteenth": {
			"alerttype": "branchclosing",
			"startdate": "6/16/2021 3:00 PM",
			"enddate": "6/19/2021 7:00 AM",
			"alertcopy": "In recognition of the Juneteenth holiday, our branches and offices will close at 3pm on Friday, June 18, 2021. <br />To see branch hours or make an appointment please visit our <a href='https://locations.mtb.com/' target='_blank'>branch locator page</a>.",
			"showpagealert": "TRUE",
			"showloginealert": "FALSE",
			"showonpersonalhp": "TRUE",
			"showonbusinesshp": "TRUE",
			"showoncommercialhp": "TRUE",
			"directurls": []
		},
		"independenceday": {
			"alerttype": "branchclosing",
			"startdate": "7/1/2021 3:00 PM",
			"enddate": "7/6/2021 7:00 AM",
			"alertcopy": "In observance of Independence Day, our branches will be closed on Monday, July 5, 2021. To see branch hours or make an appointment please visit our <a href='https://locations.mtb.com/' target='_blank'>branch locator page</a>.",
			"showpagealert": "TRUE",
			"showloginealert": "FALSE",
			"showonpersonalhp": "TRUE",
			"showonbusinesshp": "TRUE",
			"showoncommercialhp": "TRUE",
			"directurls": []
		},
		"laborday": {
			"alerttype": "branchclosing",
			"startdate": "9/2/2021 3:00 PM",
			"enddate": "9/7/2021 7:00 AM",
			"alertcopy": "In observance of Labor Day, our branches will be closed on Monday, September 6, 2021. To see branch hours or make an appointment please visit our <a href='https://locations.mtb.com/' target='_blank'>branch locator page</a>.",
			"showpagealert": "TRUE",
			"showloginealert": "FALSE",
			"showonpersonalhp": "TRUE",
			"showonbusinesshp": "TRUE",
			"showoncommercialhp": "TRUE",
			"directurls": []
		},
		"columbusday": {
			"alerttype": "branchclosing",
			"startdate": "10/7/2021 3:00 PM",
			"enddate": "10/12/2021 7:00 AM",
			"alertcopy": "In observance of Columbus Day, our branches will be closed on Monday, October 11, 2021. To see branch hours or make an appointment please visit our <a href='https://locations.mtb.com/' target='_blank'>branch locator page</a>.",
			"showpagealert": "TRUE",
			"showloginealert": "FALSE",
			"showonpersonalhp": "TRUE",
			"showonbusinesshp": "TRUE",
			"showoncommercialhp": "TRUE",
			"directurls": []
		},
		"veteransday": {
			"alerttype": "branchclosing",
			"startdate": "11/9/2021 3:00 PM",
			"enddate": "11/12/2021 7:00 AM",
			"alertcopy": "In observance of Veterans Day, our branches will be closed on Thursday, November 11, 2021. To see branch hours or make an appointment please visit our <a href='https://locations.mtb.com/' target='_blank'>branch locator page</a>.",
			"showpagealert": "TRUE",
			"showloginealert": "FALSE",
			"showonpersonalhp": "TRUE",
			"showonbusinesshp": "TRUE",
			"showoncommercialhp": "TRUE",
			"directurls": []
		},
		"thanksgivingday": {
			"alerttype": "branchclosing",
			"startdate": "11/23/2021 3:00 PM",
			"enddate": "11/26/2021 7:00 AM",
			"alertcopy": "In observance of Thanksgiving Day, our branches will be closed on Thursday, November 25, 2021. To see branch hours or make an appointment please visit our <a href='https://locations.mtb.com/' target='_blank'>branch locator page</a>.",
			"showpagealert": "TRUE",
			"showloginealert": "FALSE",
			"showonpersonalhp": "TRUE",
			"showonbusinesshp": "TRUE",
			"showoncommercialhp": "TRUE",
			"directurls": []
		},
		"christmasday": {
			"alerttype": "branchclosing",
			"startdate": "12/23/2021 3:00 PM",
			"enddate": "12/26/2021 7:00 AM",
			"alertcopy": "In observance of Christmas Day, our branches will be closed on Saturday, December 25, 2021. To see branch hours or make an appointment please visit our <a href='https://locations.mtb.com/' target='_blank'>branch locator page</a>.",
			"showpagealert": "TRUE",
			"showloginealert": "FALSE",
			"showonpersonalhp": "TRUE",
			"showonbusinesshp": "TRUE",
			"showoncommercialhp": "TRUE",
			"directurls": []
		}
	},
	"fraudgeneral": {
		"alerttype": "fraud",
		"startdate": "",
		"enddate": "",
		"alertcopy": "Beware of Scams. There has been a recent increase in customers receiving links to bogus websites and requests to remotely access their devices which have resulted in customers becoming the victim of fraud. Know the signs fraud and what to do if you're in doubt. Learn More >",
		"showpagealert": "TRUE",
		"showloginealert": "FALSE",
		"showonpersonalhp": "TRUE",
		"showonbusinesshp": "",
		"showoncommercialhp": "",
		"directurls": []
	},
	"fraudalternative": {
		"alerttype": "fraud",
		"startdate": "",
		"enddate": "",
		"alertcopy": "Protect your Personal and Financial Information During times of heightened fear and confusion, such as COVID-19, scammers are looking to gain access to your sensitive account information. We will never ask for personal account information, such as PIN, passcode, account or routing number via text or email. You will never have to click through a link to accept your funds from an email or text message. Please do not respond to any malicious and unsolicited requests that appear to be from M&T Bank.",
		"showpagealert": "TRUE",
		"showloginealert": "FALSE",
		"showonpersonalhp": "TRUE",
		"showonbusinesshp": "",
		"showoncommercialhp": "",
		"directurls": []
	},
	"impactall": {
		"alerttype": "impact",
		"startdate": "",
		"enddate": "",
		"alertcopy": "We are experiencing multiple system issues that impact branches, Customer Service call center, and online banking. Please try back later. We apologize for the inconvenience. Stay informed>",
		"showpagealert": "TRUE",
		"showloginealert": "FALSE",
		"showonpersonalhp": "TRUE",
		"showonbusinesshp": "",
		"showoncommercialhp": "",
		"directurls": []
	},
	"callcenterhighvol": {
		"alerttype": "impact",
		"startdate": "",
		"enddate": "",
		"alertcopy": "The Customer Service call center is temporarily unavailable due to higher than normal call volume. Please consider calling back later or using online or mobile banking.",
		"showpagealert": "TRUE",
		"showloginealert": "FALSE",
		"showonpersonalhp": "TRUE",
		"showonbusinesshp": "",
		"showoncommercialhp": "",
		"directurls": []
	},
	"callcenteronlyclosing": {
		"alerttype": "impact",
		"startdate": "",
		"enddate": "",
		"alertcopy": "The Customer Service call center is temporarily unavailable. Please consider calling back later. Stay Informed >",
		"showpagealert": "TRUE",
		"showloginealert": "FALSE",
		"showonpersonalhp": "TRUE",
		"showonbusinesshp": "",
		"showoncommercialhp": "",
		"directurls": []
	},
	"branchonlyclosing": {
		"alerttype": "impact",
		"startdate": "",
		"enddate": "",
		"alertcopy": "Branches in your area may be closed due to <WEATHER/ISSUE>. Visit our <a href='https://locations.mtb.com/' target='_blank'>Branch/ATM directory</a> for specific branch hours and information, and online and mobile banking are always open. Stay informed>",
		"showpagealert": "TRUE",
		"showloginealert": "FALSE",
		"showonpersonalhp": "TRUE",
		"showonbusinesshp": "",
		"showoncommercialhp": "",
		"directurls": []
	},
	"olboutage": {
		"alerttype": "impact",
		"startdate": "",
		"enddate": "",
		"alertcopy": "M&T Online Banking is temporarily unavailable. If you have any questions regarding your personal M&T accounts or you would like to complete a transaction, please call <a href='tel:1-800-724-2440' target='_blank'>1-800-724-2440</a>. We apologize for the inconvenience.",
		"showpagealert": "TRUE",
		"showloginealert": "FALSE",
		"showonpersonalhp": "TRUE",
		"showonbusinesshp": "",
		"showoncommercialhp": "",
		"directurls": []
	},

	"ao": {
		"alerttype": "service",
		"startdate": "",
		"enddate": "",
		"alertcopy": "Online account opening is temporarily unavailable and we’re working to resolve the issue. We apologize for the inconvenience. For assistance, please <a href='https://www04.timetrade.com/app/mtcorp/workflows/mtcorp-LPA/schedule?&appointmentTypeGroupId=personalbranch&appointmentTypeId=personalnewacctbranch&resourceId=any&ch=OCT' target='_blank'>Make an Appointment</a>.",
		"showpagealert": "TRUE",
		"showloginealert": "FALSE",
		"showonpersonalhp": "TRUE",
		"showonbusinesshp": "",
		"showoncommercialhp": "",
		"directurls": [],
		"status": "green"
	},
	"billpay": {
		"alerttype": "service",
		"startdate": "",
		"enddate": "",
		"alertcopy": "Bill Pay is temporarily unavailable and we’re working to resolve the issue. We apologize for the inconvenience.",
		"showpagealert": "TRUE",
		"showloginealert": "FALSE",
		"showonpersonalhp": "TRUE",
		"showonbusinesshp": "",
		"showoncommercialhp": "",
		"directurls": [],
		"status": "green"
	},
	"alerts": {
		"alerttype": "service",
		"startdate": "",
		"enddate": "",
		"alertcopy": "M&T Alerts are temporarily unavailable and we’re working to resolve the issue. We apologize for the inconvenience.",
		"showpagealert": "TRUE",
		"showloginealert": "FALSE",
		"showonpersonalhp": "TRUE",
		"showonbusinesshp": "",
		"showoncommercialhp": "",
		"directurls": [],
		"status": "green"
	},
	"mobilebanking": {
		"alerttype": "service",
		"startdate": "",
		"enddate": "",
		"alertcopy": "M&T Mobile Banking is temporarily unavailable and we’re working to resolve the issue. We apologize for the inconvenience.",
		"showpagealert": "TRUE",
		"showloginealert": "FALSE",
		"showonpersonalhp": "TRUE",
		"showonbusinesshp": "",
		"showoncommercialhp": "",
		"directurls": [],
		"status": "green"
	},
	"moneysmart": {
		"alerttype": "service",
		"startdate": "",
		"enddate": "",
		"alertcopy": "M&T Money Smart is temporarily unavailable and we’re working to resolve the issue. We apologize for the inconvenience.",
		"showpagealert": "TRUE",
		"showloginealert": "FALSE",
		"showonpersonalhp": "TRUE",
		"showonbusinesshp": "",
		"showoncommercialhp": "",
		"directurls": [],
		"status": "green"
	},
	"olb": {
		"alerttype": "service",
		"startdate": "",
		"enddate": "",
		"alertcopy": "M&T Online Banking is temporarily unavailable and we’re working to resolve the issue. We apologize for the inconvenience.",
		"showpagealert": "TRUE",
		"showloginealert": "FALSE",
		"showonpersonalhp": "TRUE",
		"showonbusinesshp": "",
		"showoncommercialhp": "",
		"directurls": [],
		"status": "green"
	},
	"mcd": {
		"alerttype": "service",
		"startdate": "",
		"enddate": "",
		"alertcopy": "Mobile Check Deposit is temporarily unavailable and we’re working to resolve the issue. We apologize for the inconvenience.",
		"showpagealert": "TRUE",
		"showloginealert": "FALSE",
		"showonpersonalhp": "TRUE",
		"showonbusinesshp": "",
		"showoncommercialhp": "",
		"directurls": [],
		"status": "green"
	},
	"transfers": {
		"alerttype": "service",
		"startdate": "",
		"enddate": "",
		"alertcopy": "Transfers and Internal Payments through M&T Online & Mobile Banking are temporarily unavailable and we’re working to resolve the issue. We apologize for the inconvenience.",
		"showpagealert": "TRUE",
		"showloginealert": "FALSE",
		"showonpersonalhp": "TRUE",
		"showonbusinesshp": "",
		"showoncommercialhp": "",
		"directurls": [],
		"status": "green"
	},
	"zelle": {
		"alerttype": "service",
		"startdate": "",
		"enddate": "",
		"alertcopy": "Zelle is temporarily unavailable and we’re working to resolve the issue. We apologize for the inconvenience.",
		"showpagealert": "TRUE",
		"showloginealert": "FALSE",
		"showonpersonalhp": "TRUE",
		"showonbusinesshp": "",
		"showoncommercialhp": "",
		"directurls": [],
		"status": "green"
	}

}