
var errorMsg = {
    PAIConfirmEligble: "Please confirm your eligibility before continuing.",
    FieldBlank: function (x) { return x + " is required." },
    SecurtyAnswerBlank: function (n) { return " Answer to Security Question "+n+" is required." },
    BadFormat: function (l, x) { return l + " must be in "+x+" format." },
    NoSpecialChars: function (l) { return l + " cannot have special characters." },
    MaxChars: function (l, n) { return l + " cannot have more than " + n + " characters." },
    MinChars: function (l, n) { return l + " must have a minimum of " + n + " characters." },
    MinCharsAnswers: function (l, n) { return         l + " must include a minimum of " + n + " characters."},
    WTSSOStart: "User ID cannot begin with 'WTSSO'.",
    PasscodeUCase: "Passcode must include at least one UPPER case letter.",
    PasscodeLCase: "Passcode must include at least one lower case letter.",
    PasscodeULCase: "Passcode must include at least one UPPER and one lower case letter.",
    CompanyNameNoSpecialChars: "Company Name cannot include the following special characters: %  }  ]  \"  <  >  ~ .",
    PasscodeNoSpecialChars: "Passcode cannot include the following special characters: &#*",
    PasscodeMisMatch: "Passcodes do not match. <br />Please re-enter your Passcodes.",
    PasscodeSameId: "Passcode cannot be the same as User ID.",
    RepeatingChars: function (l,n) { return l+" cannot include more than "+n+" repeating characters." },
    EmailFormat: " Email Address must be in the format <i>name@example.com</i>.",
    UniqueAnswers: "Answers to Security Questions must be unique.",
    AgreemntNotAccepted: function (l) { return " Acceptance of the "+l+" is required to enroll in Online Banking." },    
    NotValid: function (l) { return "Please enter a valid " + l + "." },
    PINChars: "PIN must be 4 digits.",
    NotEligible: "You are not eligible to open this account.",
    NeedsAddedAccounts: "You must enter an account number to enroll.",
    NoSpaces: function (l) { return l + " cannot include spaces." },
    NoLetters: function (l) { return l + " cannot include letters." },
    NoNumbers: function (l) { return l + " cannot include numbers." },
    SecurityAnswerFormat: function (l) { return l + " must include at least one letter or number." },
    SecurityPinFormat: function (l, n) { return l + " must be " + n + " digits." },
    AddAccountFail: "Placeholder - There was an error attempting to add your additional accounts.",
    CardsNotAllowed: "You must enter an account number to enroll.",
    MOE40081: "This User ID is already in use. Please create a new User ID.",
    StartsWithZeroPageLevelMsg: "You must enter an account number to enroll.",
    AccountNumIneligible: "You have entered ineligible account information"
};